=== Mjeda123/FFOS/FFOS_Metapodaci/Vježbe/Vježbe11/filmovi_mjeda.xsd
<?xml version="1.0" encoding="utf-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" 
targetNamespace="http://www.w3schools.com" 
xmlns="http://www.w3schools.com" 
elementFormDefault="qualified"> 


<xs:element name="filmovi"> 
<xs:complexType> 
<xs:sequence>

    <xs:element name="film" maxOccurs="unbounded" >
    <xs:complexType> 
    <xs:sequence>

        <xs:element name="naslov" type="xs:string"/> 
        <xs:element name="autor" maxOccurs="3" type="xs:string"/>

        <xs:element name="kategorija" minOccurs="0">
 	       <xs:simpleType> 
		       <xs:restriction base="xs:string">
 			     <xs:enumeration value="povijesni"/>
		 	     <xs:enumeration value="povijesni"/>
 		       </xs:restriction> 
	        </xs:simpleType>
          </xs:element> 

    </xs:sequence> 
    </xs:complexType> 
    </xs:element>



</xs:sequence> 
</xs:complexType> 
</xs:element>


</xs:schema>

=== Mjeda123/FFOS/FFOS_Metapodaci/Vježbe/Vježbe11/filmovi_mjeda.xml
<?xml version="1.0" encoding="utf-8" ?>
<filmovi xmlns="http://www.w3schools.com" 
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:schemaLocation="http://www.w3schools.com filmovi_mjeda.xsd"> 
 

<film>
    <naslov>Sedam samuraja</naslov>
    <autor>Akira Kurosawa</autor> 
    <kategorija>povijesni</kategorija> 
</film>

<film>
    <naslov>Ran</naslov>
    <autor>Akira Kurosawa</autor> 
    <kategorija>povijesni</kategorija> 
</film>
 


</filmovi>
